# 로컬 미리보기용(GitHub Pages는 자체 빌드하므로 배포엔 불필요).
#   cd site && bundle install && bundle exec jekyll serve
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
